# Generated by Django 5.0.4 on 2024-05-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
