# Generated by Django 5.0.4 on 2024-05-24 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0002_alter_mediafile_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(blank='True', upload_to='images/')),
                ('display_photo1', models.ImageField(blank='false', upload_to='images/')),
                ('display_photo2', models.ImageField(blank='false', upload_to='images/')),
                ('display_photo3', models.ImageField(blank='false', upload_to='images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
